name: build-linux-runtime-image

on:
  push:
    branches: [ dev ]

jobs:
  build-linux-runtime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & push runtime builder image
        run: |
            chmod +x .runtime_builder/linux/publish.sh
            .runtime_builder/linux/publish.sh ubuntu18-gcc9